<?php
// +----------------------------------------------------------------------
// | kaadonadmin框架 [ kaadonadmin框架 ]
// +----------------------------------------------------------------------
// | 版权所有 2020~2024 kaadon.com
// +----------------------------------------------------------------------
// | 官方网站: https://kaadon.kaadon.com
// +----------------------------------------------------------------------
// | Author: kaadon <kaadon.com@gmail.com>
// +----------------------------------------------------------------------

namespace app\common\model;

use think\Model;

/*
 * @Description: 模型基类
 * @Autor: zs
 * @Date: 2021-05-25 16:12:33
 * @LastEditors: zs
 * @LastEditTime: 2021-05-25 16:14:10
 */
class BaseModel extends Model
{
    /**
     * 自动时间戳类型
     *
     */
    protected $autoWriteTimestamp = 'int';
    /**
     * 添加时间
     *
     */
    protected $createTime = 'create_time';

    /**
     * 更新时间
     *
     */
    protected $updateTime = 'update_time';

    /**
     * @param array $data
     * @return int|string
     */
    public function insertGetId(array $data)
    {
        $selfClass                    = (new self());
        $data[$selfClass->createTime] = $data[$selfClass->updateTime] = time();
        return parent::insertGetId($data); // TODO: Change the autogenerated stub
    }



    /**
     * @param array $data
     * @param bool $getLastInsID
     * @return int|string
     */
    public function insert(array $data = [], bool $getLastInsID = false)
    {
        $selfClass                    = (new self());
        $data[$selfClass->createTime] = $data[$selfClass->updateTime] = time();
        return parent::insert($data, $getLastInsID); // TODO: Change the autogenerated stub
    }


    /**
     * @param array $data
     * @param array $allowField
     * @param bool $replace
     * @param string $suffix
     * @return Model
     */
    public static function create(array $data, array $allowField = [], bool $replace = false, string $suffix = ''): Model
    {
        $selfClass                    = (new self());
        $data[$selfClass->createTime] = $data[$selfClass->updateTime] = time();
        return parent::create($data, $allowField, $replace, $suffix); // TODO: Change the autogenerated stub
    }

    /**
     * @param array $dataSet
     * @param int $limit
     * @return int
     */
    public function insertAll(array $dataSet = [], int $limit = 0): int
    {
        foreach ($dataSet as $key => $item) {
            $dataSet[$key][$this->createTime] = $dataSet[$key][$this->updateTime] = time();
        }
        return parent::insertAll($dataSet, $limit); // TODO: Change the autogenerated stub
    }
}
